name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: rustup update 1.72 --no-self-update && rustup default 1.72
    - run: cargo build --all-targets
    - run: cargo test --all-targets
    - run: rustup component add rustfmt
    - run: cargo fmt --check
