name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        toolchain:
          - stable
          - 1.72
    name: cargo test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - name: Cargo test
        run: cargo test
      - name: Cargo clippy
        run: cargo clippy

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
